### ISSUE TITLE
Search API sometimes returns null entries in the Files list after files have been deleted

### ISSUE THREAD

**Issue by samueldjack** [hibernating-rhinos/RavenFS#12]
I can't consistently reproduce this, but I've seen an issue where, after I've deleted a file, the /search api will return a null value in the place where the file would have been in the list. 

When I break in the SearchController, I can see that Search.Query is still returning the deleted file, but the call to accessor.ReadFile for that key returns null.

**Comment by ayende** [comment]
I filtered it out and pushed
