### ISSUE TITLE
Multi-threading bug when executing searches and adding/deleting files at the same time

### ISSUE THREAD

**Issue by samueldjack** [hibernating-rhinos/RavenFS#26]
I spotted this issue when the server threw an exception (I think it was something like a SearcherClosed exception) during a search whilst it was also processing add file requests.

From the code, it looks like ReplaceSearcher is always called inside a lock, but use of the searcher isn't protected by a lock.

**Comment by ayende** [comment]
Yes, this is a known issue, I need to pull the searcher stuff from RavenDB
to handle this properly

On Fri, Mar 30, 2012 at 10:51 AM, Samuel Jack <
reply@reply.github.com
