### ISSUE TITLE
EsentWriteConflictException when trying to upload many files in a batch through the UI

### ISSUE THREAD

**Issue by samueldjack** [hibernating-rhinos/RavenFS#35]
When I select a lot of files (around 200 in this case) to upload in one go through the U I quite often see some of the files fail to upload, with this exception having been thrown.

System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: System.Net.WebException: The remote server returned an error: NotFound.
   at System.Net.Browser.ClientHttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Func`2.Invoke(T arg)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise)
{"ExceptionType":"Microsoft.Isam.Esent.Interop.EsentWriteConflictException","Message":"Write lock failed due to outstanding write lock","StackTrace":"   at Microsoft.Isam.Esent.Interop.Api.Check(Int32 err) in C:\\Work\\ravendb\\SharedLibs\\Sources\\managedesent-61618\\EsentInterop\\Api.cs:line 2739\r\n   at Microsoft.Isam.Esent.Interop.Api.JetDelete(JET_SESID sesid, JET_TABLEID tableid) in C:\\Work\\ravendb\\SharedLibs\\Sources\\managedesent-61618\\EsentInterop\\Api.cs:line 2341\r\n   at RavenFS.Storage.StorageActionsAccessor.Delete(String filename) in C:\\Projects\\HibernatingRhinos\\RavenFS\\RavenFS\\RavenFS\\Storage\\StorageActionsAccessor.cs:line 371\r\n   at RavenFS.Controllers.FilesController.<>c__DisplayClass21.<Put>b__1c(StorageActionsAccessor accessor) in C:\\Projects\\HibernatingRhinos\\RavenFS\\RavenFS\\RavenFS\\Controllers\\FilesController.cs:line 130\r\n   at RavenFS.Storage.TransactionalStorage.ExecuteBatch(Action`1 action) in C:\Projects\HibernatingRhinos\RavenFS\RavenFS\RavenFS\Storage\TransactionalStorage.cs:line 244\r\n   at RavenFS.Storage.TransactionalStorage.Batch(Action`1 action) in C:\\Projects\\HibernatingRhinos\\RavenFS\\RavenFS\\RavenFS\\Storage\\TransactionalStorage.cs:line 222\r\n   at RavenFS.Controllers.FilesController.Put(String name) in C:\\Projects\\HibernatingRhinos\\RavenFS\\RavenFS\\RavenFS\\Controllers\\FilesController.cs:line 128\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.Execute(HttpControllerContext controllerContext, IDictionary`2 arguments)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<>c__DisplayClass2.<InvokeActionAsync>b__0()\r\n   at System.Threading.Tasks.TaskHelpers.RunSynchronously[TResult](Func`1 func, CancellationToken cancellationToken)","InnerException":null}
   at RavenFS.Client.ExceptionExtensions.<TryThrowBetteError>b__0(Task task)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: System.Net.WebException: The remote server returned an error: NotFound.
   at System.Net.Browser.ClientHttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Func`2.Invoke(T arg)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise)
{"ExceptionType":"Microsoft.Isam.Esent.Interop.EsentWriteConflictException","Message":"Write lock failed due to outstanding write lock","StackTrace":"   at Microsoft.Isam.Esent.Interop.Api.Check(Int32 err) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Api.cs:line 2739\r\n   at Microsoft.Isam.Esent.Interop.Api.JetDelete(JET_SESID sesid, JET_TABLEID tableid) in C:\Work\ravendb\SharedLibs\Sources\managedesent-61618\EsentInterop\Api.cs:line 2341\r\n   at RavenFS.Storage.StorageActionsAccessor.Delete(String filename) in C:\Projects\HibernatingRhinos\RavenFS\RavenFS\RavenFS\Storage\StorageActionsAccessor.cs:line 371\r\n   at RavenFS.Controllers.FilesController.<>c__DisplayClass21.<Put>b__1c(StorageActionsAccessor accessor) in C:\Projects\HibernatingRhinos\RavenFS\RavenFS\RavenFS\Controllers\FilesController.cs:line 130\r\n   at RavenFS.Storage.TransactionalStorage.ExecuteBatch(Action`1 action) in C:\\Projects\\HibernatingRhinos\\RavenFS\\RavenFS\\RavenFS\\Storage\\TransactionalStorage.cs:line 244\r\n   at RavenFS.Storage.TransactionalStorage.Batch(Action`1 action) in C:\Projects\HibernatingRhinos\RavenFS\RavenFS\RavenFS\Storage\TransactionalStorage.cs:line 222\r\n   at RavenFS.Controllers.FilesController.Put(String name) in C:\Projects\HibernatingRhinos\RavenFS\RavenFS\RavenFS\Controllers\FilesController.cs:line 128\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.Execute(HttpControllerContext controllerContext, IDictionary`2 arguments)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<>c__DisplayClass2.<InvokeActionAsync>b__0()\r\n   at System.Threading.Tasks.TaskHelpers.RunSynchronously[TResult](Func`1 func, CancellationToken cancellationToken)","InnerException":null}
   at RavenFS.Client.ExceptionExtensions.<TryThrowBetteError>b__0(Task task)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by ayende** [comment]
Known issue, already fixed in the replication branch, when we merge it, you won't see the error.
