### ISSUE TITLE
Concurrency Esent exceptions

### ISSUE THREAD

**Issue by arekpalinski** [hibernating-rhinos/RavenFS#43]
While doing some concurrent operations with the same file Esent throws some exceptions i.e. EsentWriteConflictException. What kind of experience should we then provide user with? In RavenDB there is thrown ConcurrencyException in such cases - should we copy that way to handle that?

**Comment by ayende** [comment]
Yes, such a thing can be thrown if you have two threads that write to the
same row, it will be thrown.
You have to discard the transaction and retry.
Most of the time, it is an issue if we are modifying the same thing
concurrently

On Tue, Jun 19, 2012 at 3:33 PM, Arkadiusz Paliński <
reply@reply.github.com
